# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- bash: echo This is a script that could use $BINTRAY-USER
  env:
    BINTRAY-USER: $(bintray-user)
    BINTRAY-APIKEY: $(bintray-apikey)

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    options: '-Pbintray-user=$(bintray-user) -Pbintray-apikey=$(bintray-apikey)'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'clean build bintrayUpload'

- task: CopyFiles@2
  inputs:
    contents: '**/*.aar'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'aars'
    artifactType: 'container'
